<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eugene Nesterenko">
<meta name="dcterms.date" content="2023-05-14">

<title>Flights from NYC airports</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Flights_NYC_files/libs/clipboard/clipboard.min.js"></script>
<script src="Flights_NYC_files/libs/quarto-html/quarto.js"></script>
<script src="Flights_NYC_files/libs/quarto-html/popper.min.js"></script>
<script src="Flights_NYC_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Flights_NYC_files/libs/quarto-html/anchor.min.js"></script>
<link href="Flights_NYC_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Flights_NYC_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Flights_NYC_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Flights_NYC_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Flights_NYC_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#data-manipulation" id="toc-data-manipulation" class="nav-link active" data-scroll-target="#data-manipulation">Data Manipulation</a>
  <ul class="collapse">
  <li><a href="#problem-1-use-logical-operators-to-find-flights-that" id="toc-problem-1-use-logical-operators-to-find-flights-that" class="nav-link" data-scroll-target="#problem-1-use-logical-operators-to-find-flights-that">Problem 1: Use logical operators to find flights that:</a></li>
  <li><a href="#problem-2-what-months-had-the-highest-and-lowest-proportion-of-cancelled-flights-interpret-any-seasonal-patterns.-to-determine-if-a-flight-was-cancelled-use-the-following-code" id="toc-problem-2-what-months-had-the-highest-and-lowest-proportion-of-cancelled-flights-interpret-any-seasonal-patterns.-to-determine-if-a-flight-was-cancelled-use-the-following-code" class="nav-link" data-scroll-target="#problem-2-what-months-had-the-highest-and-lowest-proportion-of-cancelled-flights-interpret-any-seasonal-patterns.-to-determine-if-a-flight-was-cancelled-use-the-following-code">Problem 2: What months had the highest and lowest proportion of cancelled flights? Interpret any seasonal patterns. To determine if a flight was cancelled use the following code</a></li>
  <li><a href="#problem-3-what-plane-specified-by-the-tailnum-variable-traveled-the-most-times-from-new-york-city-airports-in-2013-please-left_join-the-resulting-table-with-the-table-planes-also-included-in-the-nycflights13-package." id="toc-problem-3-what-plane-specified-by-the-tailnum-variable-traveled-the-most-times-from-new-york-city-airports-in-2013-please-left_join-the-resulting-table-with-the-table-planes-also-included-in-the-nycflights13-package." class="nav-link" data-scroll-target="#problem-3-what-plane-specified-by-the-tailnum-variable-traveled-the-most-times-from-new-york-city-airports-in-2013-please-left_join-the-resulting-table-with-the-table-planes-also-included-in-the-nycflights13-package.">Problem 3: What plane (specified by the <code>tailnum</code> variable) traveled the most times from New York City airports in 2013? Please <code>left_join()</code> the resulting table with the table <code>planes</code> (also included in the <code>nycflights13</code> package).</a></li>
  <li><a href="#problem-4-the-nycflights13-package-includes-a-table-weather-that-describes-the-weather-during-2013.-use-that-table-to-answer-the-following-questions" id="toc-problem-4-the-nycflights13-package-includes-a-table-weather-that-describes-the-weather-during-2013.-use-that-table-to-answer-the-following-questions" class="nav-link" data-scroll-target="#problem-4-the-nycflights13-package-includes-a-table-weather-that-describes-the-weather-during-2013.-use-that-table-to-answer-the-following-questions">Problem 4: The <code>nycflights13</code> package includes a table (<code>weather</code>) that describes the weather during 2013. Use that table to answer the following questions:</a></li>
  <li><a href="#problem-5-use-the-flights-and-planes-tables-to-answer-the-following-questions" id="toc-problem-5-use-the-flights-and-planes-tables-to-answer-the-following-questions" class="nav-link" data-scroll-target="#problem-5-use-the-flights-and-planes-tables-to-answer-the-following-questions">Problem 5: Use the <code>flights</code> and <code>planes</code> tables to answer the following questions:</a></li>
  <li><a href="#problem-6-use-the-flights-and-planes-tables-to-answer-the-following-questions" id="toc-problem-6-use-the-flights-and-planes-tables-to-answer-the-following-questions" class="nav-link" data-scroll-target="#problem-6-use-the-flights-and-planes-tables-to-answer-the-following-questions">Problem 6: Use the <code>flights</code> and <code>planes</code> tables to answer the following questions:</a></li>
  <li><a href="#problem-7-use-the-nycflights13-to-answer-the-following-questions" id="toc-problem-7-use-the-nycflights13-to-answer-the-following-questions" class="nav-link" data-scroll-target="#problem-7-use-the-nycflights13-to-answer-the-following-questions">Problem 7: Use the <code>nycflights13</code> to answer the following questions:</a></li>
  <li><a href="#problem-8-lets-take-a-closer-look-at-what-carriers-service-the-route-to-san-francisco-international-sfo.-join-the-flights-and-airlines-tables-and-count-which-airlines-flew-the-most-to-sfo.-produce-a-new-dataframe-fly_into_sfo-that-contains-three-variables-the-name-of-the-airline-e.g.-united-air-lines-inc.-not-ua-the-count-number-of-times-it-flew-to-sfo-and-the-percent-of-the-trips-that-that-particular-airline-flew-to-sfo." id="toc-problem-8-lets-take-a-closer-look-at-what-carriers-service-the-route-to-san-francisco-international-sfo.-join-the-flights-and-airlines-tables-and-count-which-airlines-flew-the-most-to-sfo.-produce-a-new-dataframe-fly_into_sfo-that-contains-three-variables-the-name-of-the-airline-e.g.-united-air-lines-inc.-not-ua-the-count-number-of-times-it-flew-to-sfo-and-the-percent-of-the-trips-that-that-particular-airline-flew-to-sfo." class="nav-link" data-scroll-target="#problem-8-lets-take-a-closer-look-at-what-carriers-service-the-route-to-san-francisco-international-sfo.-join-the-flights-and-airlines-tables-and-count-which-airlines-flew-the-most-to-sfo.-produce-a-new-dataframe-fly_into_sfo-that-contains-three-variables-the-name-of-the-airline-e.g.-united-air-lines-inc.-not-ua-the-count-number-of-times-it-flew-to-sfo-and-the-percent-of-the-trips-that-that-particular-airline-flew-to-sfo.">Problem 8: Let’s take a closer look at what carriers service the route to San Francisco International (SFO). Join the <code>flights</code> and <code>airlines</code> tables and count which airlines flew the most to SFO. Produce a new dataframe, <code>fly_into_sfo</code> that contains three variables: the <code>name</code> of the airline, e.g., <code>United Air Lines Inc.</code> not <code>UA</code>, the count (number) of times it flew to SFO, and the <code>percent</code> of the trips that that particular airline flew to SFO.</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Flights from NYC airports</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eugene Nesterenko </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 14, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="cell">

</div>
<section id="data-manipulation" class="level1">
<h1>Data Manipulation</h1>
<section id="problem-1-use-logical-operators-to-find-flights-that" class="level2">
<h2 class="anchored" data-anchor-id="problem-1-use-logical-operators-to-find-flights-that">Problem 1: Use logical operators to find flights that:</h2>
<pre><code>-   Had an arrival delay of two or more hours (\&gt; 120 minutes)
-   Flew to Houston (IAH or HOU)
-   Were operated by United (`UA`), American (`AA`), or Delta (`DL`)
-   Departed in summer (July, August, and September)
-   Arrived more than two hours late, but didn't leave late
-   Were delayed by at least an hour, but made up over 30 minutes in flight</code></pre>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(flights) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 336,776
Columns: 19
$ year           &lt;int&gt; 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2…
$ month          &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ day            &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ dep_time       &lt;int&gt; 517, 533, 542, 544, 554, 554, 555, 557, 557, 558, 558, …
$ sched_dep_time &lt;int&gt; 515, 529, 540, 545, 600, 558, 600, 600, 600, 600, 600, …
$ dep_delay      &lt;dbl&gt; 2, 4, 2, -1, -6, -4, -5, -3, -3, -2, -2, -2, -2, -2, -1…
$ arr_time       &lt;int&gt; 830, 850, 923, 1004, 812, 740, 913, 709, 838, 753, 849,…
$ sched_arr_time &lt;int&gt; 819, 830, 850, 1022, 837, 728, 854, 723, 846, 745, 851,…
$ arr_delay      &lt;dbl&gt; 11, 20, 33, -18, -25, 12, 19, -14, -8, 8, -2, -3, 7, -1…
$ carrier        &lt;chr&gt; "UA", "UA", "AA", "B6", "DL", "UA", "B6", "EV", "B6", "…
$ flight         &lt;int&gt; 1545, 1714, 1141, 725, 461, 1696, 507, 5708, 79, 301, 4…
$ tailnum        &lt;chr&gt; "N14228", "N24211", "N619AA", "N804JB", "N668DN", "N394…
$ origin         &lt;chr&gt; "EWR", "LGA", "JFK", "JFK", "LGA", "EWR", "EWR", "LGA",…
$ dest           &lt;chr&gt; "IAH", "IAH", "MIA", "BQN", "ATL", "ORD", "FLL", "IAD",…
$ air_time       &lt;dbl&gt; 227, 227, 160, 183, 116, 150, 158, 53, 140, 138, 149, 1…
$ distance       &lt;dbl&gt; 1400, 1416, 1089, 1576, 762, 719, 1065, 229, 944, 733, …
$ hour           &lt;dbl&gt; 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6…
$ minute         &lt;dbl&gt; 15, 29, 40, 45, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 0…
$ time_hour      &lt;dttm&gt; 2013-01-01 05:00:00, 2013-01-01 05:00:00, 2013-01-01 0…</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Had an arrival delay of two or more hours (&gt; 120 minutes)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(arr_delay <span class="sc">&gt;</span> <span class="dv">120</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10,034 × 19
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;          &lt;int&gt;
 1  2013     1     1      811            630       101     1047            830
 2  2013     1     1      848           1835       853     1001           1950
 3  2013     1     1      957            733       144     1056            853
 4  2013     1     1     1114            900       134     1447           1222
 5  2013     1     1     1505           1310       115     1638           1431
 6  2013     1     1     1525           1340       105     1831           1626
 7  2013     1     1     1549           1445        64     1912           1656
 8  2013     1     1     1558           1359       119     1718           1515
 9  2013     1     1     1732           1630        62     2028           1825
10  2013     1     1     1803           1620       103     2008           1750
# ℹ 10,024 more rows
# ℹ 11 more variables: arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;,
#   tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;,
#   hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Flew to Houston (IAH or HOU)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># filter for multiple destinations using OR operator</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dest <span class="sc">==</span> <span class="st">"IAH"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"HOU"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9,313 × 19
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;          &lt;int&gt;
 1  2013     1     1      517            515         2      830            819
 2  2013     1     1      533            529         4      850            830
 3  2013     1     1      623            627        -4      933            932
 4  2013     1     1      728            732        -4     1041           1038
 5  2013     1     1      739            739         0     1104           1038
 6  2013     1     1      908            908         0     1228           1219
 7  2013     1     1     1028           1026         2     1350           1339
 8  2013     1     1     1044           1045        -1     1352           1351
 9  2013     1     1     1114            900       134     1447           1222
10  2013     1     1     1205           1200         5     1503           1505
# ℹ 9,303 more rows
# ℹ 11 more variables: arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;,
#   tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;,
#   hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Were operated by United (`UA`), American (`AA`), or Delta (`DL`)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># filter for multiple carriers using a vector (list) of possible values</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(carrier <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"UA"</span>,<span class="st">"AA"</span>,<span class="st">"DL"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 139,504 × 19
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;          &lt;int&gt;
 1  2013     1     1      517            515         2      830            819
 2  2013     1     1      533            529         4      850            830
 3  2013     1     1      542            540         2      923            850
 4  2013     1     1      554            600        -6      812            837
 5  2013     1     1      554            558        -4      740            728
 6  2013     1     1      558            600        -2      753            745
 7  2013     1     1      558            600        -2      924            917
 8  2013     1     1      558            600        -2      923            937
 9  2013     1     1      559            600        -1      941            910
10  2013     1     1      559            600        -1      854            902
# ℹ 139,494 more rows
# ℹ 11 more variables: arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;,
#   tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;,
#   hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Departed in summer (July, August, and September)</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># filter for multiple months using a vector of possible numerical month values</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(month <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 86,326 × 19
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;          &lt;int&gt;
 1  2013     7     1        1           2029       212      236           2359
 2  2013     7     1        2           2359         3      344            344
 3  2013     7     1       29           2245       104      151              1
 4  2013     7     1       43           2130       193      322             14
 5  2013     7     1       44           2150       174      300            100
 6  2013     7     1       46           2051       235      304           2358
 7  2013     7     1       48           2001       287      308           2305
 8  2013     7     1       58           2155       183      335             43
 9  2013     7     1      100           2146       194      327             30
10  2013     7     1      100           2245       135      337            135
# ℹ 86,316 more rows
# ℹ 11 more variables: arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;,
#   tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;,
#   hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrived more than two hours late, but didn't leave late</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># filter with criteria for departure and arrival delay using AND operator</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dep_delay <span class="sc">&lt;=</span> <span class="dv">0</span> <span class="sc">&amp;</span> arr_delay <span class="sc">&gt;</span> <span class="dv">120</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 29 × 19
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;          &lt;int&gt;
 1  2013     1    27     1419           1420        -1     1754           1550
 2  2013    10     7     1350           1350         0     1736           1526
 3  2013    10     7     1357           1359        -2     1858           1654
 4  2013    10    16      657            700        -3     1258           1056
 5  2013    11     1      658            700        -2     1329           1015
 6  2013     3    18     1844           1847        -3       39           2219
 7  2013     4    17     1635           1640        -5     2049           1845
 8  2013     4    18      558            600        -2     1149            850
 9  2013     4    18      655            700        -5     1213            950
10  2013     5    22     1827           1830        -3     2217           2010
# ℹ 19 more rows
# ℹ 11 more variables: arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;,
#   tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;,
#   hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Were delayed by at least an hour, but made up over 30 minutes in flight</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># filter with criteria for departure and make up time using sequential filters</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dep_delay <span class="sc">&gt;=</span> <span class="dv">60</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>((dep_delay <span class="sc">-</span> arr_delay) <span class="sc">&gt;</span> <span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,844 × 19
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;          &lt;int&gt;
 1  2013     1     1     2205           1720       285       46           2040
 2  2013     1     1     2326           2130       116      131             18
 3  2013     1     3     1503           1221       162     1803           1555
 4  2013     1     3     1839           1700        99     2056           1950
 5  2013     1     3     1850           1745        65     2148           2120
 6  2013     1     3     1941           1759       102     2246           2139
 7  2013     1     3     1950           1845        65     2228           2227
 8  2013     1     3     2015           1915        60     2135           2111
 9  2013     1     3     2257           2000       177       45           2224
10  2013     1     4     1917           1700       137     2135           1950
# ℹ 1,834 more rows
# ℹ 11 more variables: arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;,
#   tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;,
#   hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
</div>
</div>
<p>We have found an unusual result for the <em>Arrived more than two hours late, but didn’t leave late</em> filter. It must be the case of currupted data - we can hardly imagine flights that spent more than additional 1000 minutes in the air (arrival time delay was over 1000 minutes with non-positive departure delay)</p>
</section>
<section id="problem-2-what-months-had-the-highest-and-lowest-proportion-of-cancelled-flights-interpret-any-seasonal-patterns.-to-determine-if-a-flight-was-cancelled-use-the-following-code" class="level2">
<h2 class="anchored" data-anchor-id="problem-2-what-months-had-the-highest-and-lowest-proportion-of-cancelled-flights-interpret-any-seasonal-patterns.-to-determine-if-a-flight-was-cancelled-use-the-following-code">Problem 2: What months had the highest and lowest proportion of cancelled flights? Interpret any seasonal patterns. To determine if a flight was cancelled use the following code</h2>
<!-- -->
<pre><code>flights %&gt;% 
  filter(is.na(dep_time)) </code></pre>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What months had the highest and lowest % of cancelled flights?</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># First, we create two dataframes - cancelled flights and total flights - with summary statistics</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Cancelled flights dataframe</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>cancelled_flights <span class="ot">&lt;-</span> flights <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># filter for NA values</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(dep_time)) <span class="sc">%&gt;%</span>   </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># grouping dataset by months to calculate summary statistics</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month) <span class="sc">%&gt;%</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># dataframe is already for the cancelled flights, we just count the number of cases by month</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_cancelled =</span> <span class="fu">n</span>())   </span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Total flights dataframe</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>total_flights <span class="ot">&lt;-</span> flights <span class="sc">%&gt;%</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># no need to filter for the cancelled flights</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># grouping dataset by months to calculate summary statistics</span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month) <span class="sc">%&gt;%</span> </span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># dataframe is already for the total flights, we just count the total number of fligths by month</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_total =</span> <span class="fu">n</span>())   </span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Joining two dataframes to have counts of cancelled and total flights in one table</span></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a><span class="co"># We expect each month to have non-NA value of cancelled and total flights - hence, use inner join</span></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>cancelled_percentage_flights <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(<span class="at">x =</span> cancelled_flights, <span class="at">y =</span> total_flights, <span class="at">by =</span> <span class="st">"month"</span>)</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding new variable - percentage of cancelled flights, and arranging to find highest and lowest cases</span></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>cancelled_percentage_flights <span class="sc">%&gt;%</span> </span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add a new variable for the percentage as (N of cancelled / N of total)*100, up to 1 digit precision</span></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percentage_cancelled =</span> <span class="fu">round</span>((number_cancelled<span class="sc">/</span>number_total) <span class="sc">*</span> <span class="dv">100</span>, <span class="at">digits =</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Arranging in descending order on percentage of cancelled flights</span></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(percentage_cancelled))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
   month number_cancelled number_total percentage_cancelled
   &lt;int&gt;            &lt;int&gt;        &lt;int&gt;                &lt;dbl&gt;
 1     2             1261        24951                  5.1
 2     6             1009        28243                  3.6
 3    12             1025        28135                  3.6
 4     7              940        29425                  3.2
 5     3              861        28834                  3  
 6     4              668        28330                  2.4
 7     5              563        28796                  2  
 8     1              521        27004                  1.9
 9     8              486        29327                  1.7
10     9              452        27574                  1.6
11    11              233        27268                  0.9
12    10              236        28889                  0.8</code></pre>
</div>
</div>
<p>February has <strong>the highest</strong> proportion of cancelled flights (5.1%), while October has <strong>the lowest</strong> (0.8%). <strong>Our hypothesis is that in February weather conditions in NYC often do not permit the plane to take off</strong> (cold weather, ice on the runway, blizzard). Same factors could contribute to higher average delay time (though this hypothesis needs to be verified).</p>
<p><strong>For October-November</strong> (percentage is similar), <strong>perhaps, weather conditions are most favourable.</strong> We also see the <strong>seasonal factor only for autumn months (September - November), which indicates low percentage of cancelled flights</strong>. Other seasons do not show a clear pattern.</p>
</section>
<section id="problem-3-what-plane-specified-by-the-tailnum-variable-traveled-the-most-times-from-new-york-city-airports-in-2013-please-left_join-the-resulting-table-with-the-table-planes-also-included-in-the-nycflights13-package." class="level2">
<h2 class="anchored" data-anchor-id="problem-3-what-plane-specified-by-the-tailnum-variable-traveled-the-most-times-from-new-york-city-airports-in-2013-please-left_join-the-resulting-table-with-the-table-planes-also-included-in-the-nycflights13-package.">Problem 3: What plane (specified by the <code>tailnum</code> variable) traveled the most times from New York City airports in 2013? Please <code>left_join()</code> the resulting table with the table <code>planes</code> (also included in the <code>nycflights13</code> package).</h2>
<p>For the plane with the greatest number of flights and that had more than 50 seats, please create a table where it flew to during 2013.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Saving and printing a new table for number of flights by plane (tailnum)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>flights_by_plane <span class="ot">&lt;-</span> flights <span class="sc">%&gt;%</span>  <span class="co"># use base dataset flights as a starting point</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Selecting only year 2013</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2013</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Deleting rows with unknown tail number (otherwise distorts statistics)</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(tailnum) <span class="sc">%&gt;%</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Creating a dataframe grouped by plane</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(tailnum) <span class="sc">%&gt;%</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Counting number of flights by plane</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count_flights =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Arranging in descending order to find the plane that travelled the most</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count_flights))</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,043 × 2
   tailnum count_flights
   &lt;chr&gt;           &lt;int&gt;
 1 N725MQ            575
 2 N722MQ            513
 3 N723MQ            507
 4 N711MQ            486
 5 N713MQ            483
 6 N258JB            427
 7 N298JB            407
 8 N353JB            404
 9 N351JB            402
10 N735MQ            396
# ℹ 4,033 more rows</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Joining the data on flight count with planes details. We want to preserve data on number of flights regardless of whether the tailnumber is registered in "planes" dictionary - hence, use the left join.</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>plane_data_number_flights <span class="ot">&lt;-</span> <span class="fu">left_join</span>(<span class="at">x =</span> flights_by_plane, <span class="at">y =</span> planes, <span class="at">by =</span> <span class="st">"tailnum"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print head rows of new table to take a look at data</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(plane_data_number_flights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 10
  tailnum count_flights  year type        manufacturer model engines seats speed
  &lt;chr&gt;           &lt;int&gt; &lt;int&gt; &lt;chr&gt;       &lt;chr&gt;        &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt;
1 N725MQ            575    NA &lt;NA&gt;        &lt;NA&gt;         &lt;NA&gt;       NA    NA    NA
2 N722MQ            513    NA &lt;NA&gt;        &lt;NA&gt;         &lt;NA&gt;       NA    NA    NA
3 N723MQ            507    NA &lt;NA&gt;        &lt;NA&gt;         &lt;NA&gt;       NA    NA    NA
4 N711MQ            486  1976 Fixed wing… GULFSTREAM … G115…       2    22    NA
5 N713MQ            483    NA &lt;NA&gt;        &lt;NA&gt;         &lt;NA&gt;       NA    NA    NA
6 N258JB            427  2006 Fixed wing… EMBRAER      ERJ …       2    20    NA
# ℹ 1 more variable: engine &lt;chr&gt;</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We want to include only planes with more than 50 seats</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># For this, we would save a new table</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>plane_data_number_flights_many_seats <span class="ot">&lt;-</span> plane_data_number_flights <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Drop cases where number of seats is unknown (probably a redundant action, given the next filter)</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(seats) <span class="sc">%&gt;%</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Leave only planes with over 50 seats</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(seats <span class="sc">&gt;</span> <span class="dv">50</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># dataframe was already arrange from most frequent to least frequent flyers, no need to arrange further</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the plane with hightest number of flights that has over 50 seats</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(plane_data_number_flights_many_seats,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  tailnum count_flights  year type        manufacturer model engines seats speed
  &lt;chr&gt;           &lt;int&gt; &lt;int&gt; &lt;chr&gt;       &lt;chr&gt;        &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt;
1 N328AA            393  1986 Fixed wing… BOEING       767-…       2   255    NA
# ℹ 1 more variable: engine &lt;chr&gt;</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the most frequent flyer (tailnum) to a separate list (we don't know how to save to a single variable)</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>frequent_flyer <span class="ot">&lt;-</span> plane_data_number_flights_many_seats[<span class="dv">1</span><span class="sc">:</span><span class="dv">1</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">1</span>]</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Save and print a table containing destinanations of the most frequent flyer</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>frequent_flyer_destinations <span class="ot">&lt;-</span> flights <span class="sc">%&gt;%</span> </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Selecting only the most frequently flying plane using a newly created list</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(tailnum <span class="sc">%in%</span> frequent_flyer) <span class="sc">%&gt;%</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Selecting only year 2013</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2013</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Showing only columns for plane (tail number) and destination</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(<span class="st">"tailnum"</span>,<span class="st">"dest"</span>))</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 393 × 2
   tailnum dest 
   &lt;chr&gt;   &lt;chr&gt;
 1 N328AA  LAX  
 2 N328AA  LAX  
 3 N328AA  LAX  
 4 N328AA  LAX  
 5 N328AA  LAX  
 6 N328AA  LAX  
 7 N328AA  LAX  
 8 N328AA  LAX  
 9 N328AA  LAX  
10 N328AA  LAX  
# ℹ 383 more rows</code></pre>
</div>
</div>
<p>The unconditioned arrangement shows that plane <strong>N725MQ</strong> has the highest number of flights, 575.</p>
<p>However, if we apply the filter on number of seats (<em>more than 50</em>), the result changes: now <strong>N328AA</strong> tops the list with 393 flights. The data frame <strong>frequent_flyer_destinations</strong> shows the destinations to which plane with tail number N328AA flew in 2013 - as expected, it has 393 rows.</p>
<p>We have tried to make a code more robust, saving the variable (list) for most frequent flyer and later applying as an input for flights filter. If the dataset changes, so might change the tail number of most frequent flyer - the code supports such case.</p>
</section>
<section id="problem-4-the-nycflights13-package-includes-a-table-weather-that-describes-the-weather-during-2013.-use-that-table-to-answer-the-following-questions" class="level2">
<h2 class="anchored" data-anchor-id="problem-4-the-nycflights13-package-includes-a-table-weather-that-describes-the-weather-during-2013.-use-that-table-to-answer-the-following-questions">Problem 4: The <code>nycflights13</code> package includes a table (<code>weather</code>) that describes the weather during 2013. Use that table to answer the following questions:</h2>
<pre><code>-   What is the distribution of temperature (`temp`) in July 2013? Identify any important outliers in terms of the `wind_speed` variable.
-   What is the relationship between `dewp` and `humid`?
-   What is the relationship between `precip` and `visib`?</code></pre>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(weather)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 15
  origin  year month   day  hour  temp  dewp humid wind_dir wind_speed wind_gust
  &lt;chr&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
1 EWR     2013     1     1     1  39.0  26.1  59.4      270      10.4         NA
2 EWR     2013     1     1     2  39.0  27.0  61.6      250       8.06        NA
3 EWR     2013     1     1     3  39.0  28.0  64.4      240      11.5         NA
4 EWR     2013     1     1     4  39.9  28.0  62.2      250      12.7         NA
5 EWR     2013     1     1     5  39.0  28.0  64.4      260      12.7         NA
6 EWR     2013     1     1     6  37.9  28.0  67.2      240      11.5         NA
# ℹ 4 more variables: precip &lt;dbl&gt;, pressure &lt;dbl&gt;, visib &lt;dbl&gt;,
#   time_hour &lt;dttm&gt;</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save a dataframe for July 2013 only)</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>weather_july_2013 <span class="ot">&lt;-</span> weather <span class="sc">%&gt;%</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2013</span> <span class="sc">&amp;</span> month <span class="sc">==</span> <span class="dv">7</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Get summary statistics for July 2013, which allows to infer data about distribution and outliers for temperature and wind speed</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(weather_july_2013)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">weather_july_2013</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">2228</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">15</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">POSIXct</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">origin</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2013.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2013.00</td>
<td style="text-align: right;">2013.00</td>
<td style="text-align: right;">2013.00</td>
<td style="text-align: right;">2013.00</td>
<td style="text-align: right;">2013.00</td>
<td style="text-align: left;">▁▁▇▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">month</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: left;">▁▁▇▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">day</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">8.93</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">24.00</td>
<td style="text-align: right;">31.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">hour</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">11.51</td>
<td style="text-align: right;">6.92</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">6.00</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">18.00</td>
<td style="text-align: right;">23.00</td>
<td style="text-align: left;">▇▇▆▇▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">temp</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">80.07</td>
<td style="text-align: right;">7.12</td>
<td style="text-align: right;">64.04</td>
<td style="text-align: right;">75.02</td>
<td style="text-align: right;">78.98</td>
<td style="text-align: right;">84.20</td>
<td style="text-align: right;">100.04</td>
<td style="text-align: left;">▂▇▇▃▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">dewp</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">67.01</td>
<td style="text-align: right;">5.98</td>
<td style="text-align: right;">42.98</td>
<td style="text-align: right;">64.04</td>
<td style="text-align: right;">69.08</td>
<td style="text-align: right;">71.06</td>
<td style="text-align: right;">78.08</td>
<td style="text-align: left;">▁▁▂▇▃</td>
</tr>
<tr class="odd">
<td style="text-align: left;">humid</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">66.90</td>
<td style="text-align: right;">16.74</td>
<td style="text-align: right;">24.46</td>
<td style="text-align: right;">53.18</td>
<td style="text-align: right;">66.93</td>
<td style="text-align: right;">81.63</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: left;">▁▆▇▇▅</td>
</tr>
<tr class="even">
<td style="text-align: left;">wind_dir</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">191.19</td>
<td style="text-align: right;">95.11</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">150.00</td>
<td style="text-align: right;">210.00</td>
<td style="text-align: right;">250.00</td>
<td style="text-align: right;">360.00</td>
<td style="text-align: left;">▅▂▇▇▃</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wind_speed</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">9.58</td>
<td style="text-align: right;">4.06</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">6.90</td>
<td style="text-align: right;">9.21</td>
<td style="text-align: right;">12.66</td>
<td style="text-align: right;">25.32</td>
<td style="text-align: left;">▂▇▇▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">wind_gust</td>
<td style="text-align: right;">1975</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">21.40</td>
<td style="text-align: right;">4.26</td>
<td style="text-align: right;">16.11</td>
<td style="text-align: right;">18.41</td>
<td style="text-align: right;">20.71</td>
<td style="text-align: right;">23.02</td>
<td style="text-align: right;">66.75</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">precip</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">pressure</td>
<td style="text-align: right;">264</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">1016.65</td>
<td style="text-align: right;">5.11</td>
<td style="text-align: right;">1000.70</td>
<td style="text-align: right;">1014.00</td>
<td style="text-align: right;">1017.00</td>
<td style="text-align: right;">1020.60</td>
<td style="text-align: right;">1027.20</td>
<td style="text-align: left;">▁▂▆▇▃</td>
</tr>
<tr class="odd">
<td style="text-align: left;">visib</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">9.59</td>
<td style="text-align: right;">1.34</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: left;">▁▁▁▁▇</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: POSIXct</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">min</th>
<th style="text-align: left;">max</th>
<th style="text-align: left;">median</th>
<th style="text-align: right;">n_unique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">time_hour</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">2013-07-01</td>
<td style="text-align: left;">2013-07-31 23:00:00</td>
<td style="text-align: left;">2013-07-16 11:30:00</td>
<td style="text-align: right;">744</td>
</tr>
</tbody>
</table>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Further check the wind speed outliers. Hypothesis - wind speed of 0 is actually a missed data point</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>weather_july_2013 <span class="sc">%&gt;%</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(wind_speed <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  count
  &lt;int&gt;
1    79</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw a scatterplot to infer relationship between dew point and humidity</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(weather, <span class="fu">aes</span>(<span class="at">x =</span> dewp, <span class="at">y =</span> humid)) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Flights_NYC_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw a scatterplot to infer relationship between precipitation level and visibility</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(weather, <span class="fu">aes</span>(<span class="at">x =</span> precip, <span class="at">y =</span> visib)) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Flights_NYC_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw a scatterplot to infer relationship between precipitation level and visibility for July 2013 only</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(weather_july_2013, <span class="fu">aes</span>(<span class="at">x =</span> precip, <span class="at">y =</span> visib)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Flights_NYC_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Temperature in July 2013 has a mean of 80 degrees Fahrenheit and a standard deviation of 7.1</strong>. It also <strong>seems to be skewed to the right</strong>, with median (79 degrees) being less than mean, and 75% percentile and maximum value farther from median than 25% percentile and minimum value respectively.</p>
<p><strong>Wind speed data seems to be incomplete in July 2013, with 2 missing points and as much as 79 points with wind speed of exactly 0</strong> (unlikely result, looks more like lack of data than true case of 0 speed).</p>
<p>The scatter plot for the (dewp, humid) looks quite cumbersome, but from the shape <strong>we can infer a positive correlation - the higher the dew point, the higher the humidity.</strong> We believe these are related concepts (but not so sure on the definitions), so the correlation is expected.</p>
<p>The <strong>precipitation-visibility</strong> data shows no clear pattern on individual observations across years, and July 2013 data points to <strong>slightly positive correlation</strong>. This is <strong>counterintuitive</strong>, as we would expect rain and snow to reduce distance at which objects are visible.</p>
</section>
<section id="problem-5-use-the-flights-and-planes-tables-to-answer-the-following-questions" class="level2">
<h2 class="anchored" data-anchor-id="problem-5-use-the-flights-and-planes-tables-to-answer-the-following-questions">Problem 5: Use the <code>flights</code> and <code>planes</code> tables to answer the following questions:</h2>
<pre><code>-   How many planes have a missing date of manufacture?
-   What are the five most common manufacturers?
-   Has the distribution of manufacturer changed over time as reflected by the airplanes flying from NYC in 2013? (Hint: you may need to use case_when() to recode the manufacturer name and collapse rare vendors into a category called Other.)</code></pre>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(planes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  tailnum  year type               manufacturer model engines seats speed engine
  &lt;chr&gt;   &lt;int&gt; &lt;chr&gt;              &lt;chr&gt;        &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; 
1 N10156   2004 Fixed wing multi … EMBRAER      EMB-…       2    55    NA Turbo…
2 N102UW   1998 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…
3 N103US   1999 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…
4 N104UW   1999 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…
5 N10575   2002 Fixed wing multi … EMBRAER      EMB-…       2    55    NA Turbo…
6 N105UW   1999 Fixed wing multi … AIRBUS INDU… A320…       2   182    NA Turbo…</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a dataframe for which year of manufacture is unknown</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>planes <span class="sc">%&gt;%</span> </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(year))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 70 × 9
   tailnum  year type              manufacturer model engines seats speed engine
   &lt;chr&gt;   &lt;int&gt; &lt;chr&gt;             &lt;chr&gt;        &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; 
 1 N14558     NA Fixed wing multi… EMBRAER      EMB-…       2    55    NA Turbo…
 2 N15555     NA Fixed wing multi… EMBRAER      EMB-…       2    55    NA Turbo…
 3 N15574     NA Fixed wing multi… EMBRAER      EMB-…       2    55    NA Turbo…
 4 N174US     NA Fixed wing multi… AIRBUS INDU… A321…       2   199    NA Turbo…
 5 N177US     NA Fixed wing multi… AIRBUS INDU… A321…       2   199    NA Turbo…
 6 N181UW     NA Fixed wing multi… AIRBUS INDU… A321…       2   199    NA Turbo…
 7 N18557     NA Fixed wing multi… EMBRAER      EMB-…       2    55    NA Turbo…
 8 N194UW     NA Fixed wing multi… AIRBUS       A321…       2   199    NA Turbo…
 9 N238JB     NA Fixed wing multi… EMBRAER      ERJ …       2    20    NA Turbo…
10 N271LV     NA Fixed wing multi… BOEING       737-…       2   149    NA Turbo…
# ℹ 60 more rows</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Basic dataframe of manufacturers and number of planes</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>planes_number <span class="ot">&lt;-</span> planes <span class="sc">%&gt;%</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(manufacturer) <span class="sc">%&gt;%</span> </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Take a look at the result</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>planes_number</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 35 × 2
   manufacturer                  count
   &lt;chr&gt;                         &lt;int&gt;
 1 BOEING                         1630
 2 AIRBUS INDUSTRIE                400
 3 BOMBARDIER INC                  368
 4 AIRBUS                          336
 5 EMBRAER                         299
 6 MCDONNELL DOUGLAS               120
 7 MCDONNELL DOUGLAS AIRCRAFT CO   103
 8 MCDONNELL DOUGLAS CORPORATION    14
 9 CANADAIR                          9
10 CESSNA                            9
# ℹ 25 more rows</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new dataset with manufactureres uniformly named. Not popular names are grouped into the "OTHER" category</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>planes_renamed_manufacturers <span class="ot">&lt;-</span> planes <span class="sc">%&gt;%</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">manufacturer =</span> <span class="fu">case_when</span>(</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>     manufacturer <span class="sc">==</span> <span class="st">"BOEING"</span> <span class="sc">~</span> <span class="st">"BOEING"</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>     manufacturer <span class="sc">%in%</span>  <span class="fu">c</span>(<span class="st">"AIRBUS INDUSTRIE"</span>, <span class="st">"AIRBUS"</span>) <span class="sc">~</span> <span class="st">"AIRBUS"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>     manufacturer <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"MCDONNELL DOUGLAS"</span>,<span class="st">"MCDONNELL DOUGLAS AIRCRAFT CO"</span>,<span class="st">"MCDONNELL DOUGLAS CORPORATION"</span>) <span class="sc">~</span> <span class="st">"MCDONNELL DOUGLAS"</span>,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>     manufacturer <span class="sc">==</span> <span class="st">"BOMBARDIER INC"</span> <span class="sc">~</span> <span class="st">"BOMBARDIER INC"</span>,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>     manufacturer <span class="sc">==</span> <span class="st">"EMBRAER"</span> <span class="sc">~</span> <span class="st">"EMBRAER"</span>,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>     <span class="cn">TRUE</span>  <span class="sc">~</span> <span class="st">"OTHER"</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>   ) </span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Precise dataframe of manufacturers (using uniform naming) and number of planes</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>planes_precise_number <span class="ot">&lt;-</span> planes_renamed_manufacturers <span class="sc">%&gt;%</span> </span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(manufacturer) <span class="sc">%&gt;%</span> </span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Take a look at the result</span></span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>planes_precise_number</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  manufacturer      count
  &lt;chr&gt;             &lt;int&gt;
1 BOEING             1630
2 AIRBUS              736
3 BOMBARDIER INC      368
4 EMBRAER             299
5 MCDONNELL DOUGLAS   237
6 OTHER                52</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Attempt to store distinct planes that flew in 2013 as a list</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>distinct_flights <span class="ot">&lt;-</span> flights <span class="sc">%&gt;%</span> </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2013</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(tailnum) <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(tailnum)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Attempt to recreate the analysis, adding the filter on unique planes that flew in 2013</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>planes_precise_number_2013 <span class="ot">&lt;-</span> planes_renamed_manufacturers <span class="sc">%&gt;%</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(tailnum <span class="sc">%in%</span> <span class="fu">c</span>(distinct_flights)) <span class="sc">%&gt;%</span> </span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(manufacturer) <span class="sc">%&gt;%</span> </span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 2
# ℹ 2 variables: manufacturer &lt;chr&gt;, count &lt;int&gt;</code></pre>
</div>
</div>
<p>Table <em>planes</em> only contains information about year of manufacture. Applying the NA filter, we find that 70 planes have unknown year of manufacture.</p>
<p>The list of five most common manufacturer is provided below. Boeing tops the list with 1630 planes</p>
<table class="table">
<caption>Common manufacturers</caption>
<thead>
<tr class="header">
<th>Manufacturer</th>
<th>Number of planes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BOEING</td>
<td>1630</td>
</tr>
<tr class="even">
<td>AIRBUS INDUSTRIE</td>
<td>400</td>
</tr>
<tr class="odd">
<td>BOMBARDIER INC</td>
<td>368</td>
</tr>
<tr class="even">
<td>AIRBUS</td>
<td>336</td>
</tr>
<tr class="odd">
<td>EMBRAER</td>
<td>299</td>
</tr>
</tbody>
</table>
<p>We need to be aware, however, that grouping by might not recognize same manufacturer under different names (e.g.&nbsp;“AIRBUS INDUSTRIE” is treated separate from “AIRBUS”). To take this into account, manufacturer names in the dataset must be amended to be uniform. The hint on “case_when” might also be useful.</p>
<p>Indeed, applying the case_when and grouping all manufactures with less than 10 planes into the “OTHER” category, we get the top-5 manufacturers:</p>
<table class="table">
<thead>
<tr class="header">
<th>Manufacturer</th>
<th>Number of planes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BOEING</td>
<td>1630</td>
</tr>
<tr class="even">
<td>AIRBUS</td>
<td>736</td>
</tr>
<tr class="odd">
<td>BOMBARDIER INC</td>
<td>368</td>
</tr>
<tr class="even">
<td>EMBRAER</td>
<td>299</td>
</tr>
<tr class="odd">
<td>MCDONNELL DOUGLAS</td>
<td>237</td>
</tr>
</tbody>
</table>
<p>Others total in 52 planes</p>
<p>The general idea to understand changes in 2013 is the following:</p>
<ol type="1">
<li>Find and save a distinct list of unique planes that flew in 2013 (tailnum from flights table)</li>
<li>Use this list as an input to %in% filter for the planes_renamed_manufacturers table</li>
<li>Group the dataframe by manufacturer, summarize (count) and arrange in descending order</li>
</ol>
<p>However, tibble from point 1 (list of unique planes) does not serve as a filter input well, and we don’t know how to actually save variable as a list (vector)</p>
</section>
<section id="problem-6-use-the-flights-and-planes-tables-to-answer-the-following-questions" class="level2">
<h2 class="anchored" data-anchor-id="problem-6-use-the-flights-and-planes-tables-to-answer-the-following-questions">Problem 6: Use the <code>flights</code> and <code>planes</code> tables to answer the following questions:</h2>
<pre><code>-   What is the oldest plane (specified by the tailnum variable) that flew from New York City airports in 2013?
-   How many airplanes that flew from New York City are included in the planes table?</code></pre>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># mutate planes table to have a uniquely named column for year of manufacture</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>planes_1 <span class="ot">&lt;-</span> planes <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year_manufactured =</span> year)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="co"># mutate planes table to have a uniquely named column for year of flight</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>flights_1 <span class="ot">&lt;-</span> flights <span class="sc">%&gt;%</span> </span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year_flight =</span> year)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="co"># join the two tables to have a dataframe with both year of manufacture (to sort) and year of flight (to filter)</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="co"># We want to preserve flight data, hence we use left join</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>flights_planes <span class="ot">&lt;-</span> <span class="fu">left_join</span>(<span class="at">x =</span> flights_1, <span class="at">y =</span> planes_1, <span class="at">by =</span> <span class="st">"tailnum"</span>)</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering for planes with known year of manufacture that flew in 2013, arranging by year of manufacture</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>fights_planes_2013 <span class="ot">&lt;-</span> flights_planes <span class="sc">%&gt;%</span> </span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(year_manufactured) <span class="sc">%&gt;%</span> </span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year_flight <span class="sc">==</span> <span class="dv">2013</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(year_manufactured)</span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing the row for top 1 (the oldest plane)</span></span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fights_planes_2013,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 29
  year.x month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;          &lt;int&gt;
1   2013     1    30      741            745        -4     1059           1125
# ℹ 21 more variables: arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;,
#   tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;,
#   hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;, year_flight &lt;int&gt;,
#   year.y &lt;int&gt;, type &lt;chr&gt;, manufacturer &lt;chr&gt;, model &lt;chr&gt;, engines &lt;int&gt;,
#   seats &lt;int&gt;, speed &lt;int&gt;, engine &lt;chr&gt;, year_manufactured &lt;int&gt;</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a new dataframe that contains only those planes from planes table that are also listed in flights table</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>flights_planes_semi_joined <span class="ot">&lt;-</span> <span class="fu">semi_join</span>(<span class="at">x =</span> planes, <span class="at">y =</span> flights, <span class="at">by =</span> <span class="st">"tailnum"</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Count number of planes in &lt;potentially&gt; reduced data. Planes table already has distinct values for planes</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(flights_planes_semi_joined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
      n
  &lt;int&gt;
1  3322</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare to number of planes in original (not reduced) data</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(planes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
      n
  &lt;int&gt;
1  3322</code></pre>
</div>
</div>
<p>N381AA is the oldest plane (manufactured in 1956) that flew from NYC in 2013. Technically, it might not be the only plane that was manufactured in 2013 (ordering does not indicate distinct values), but there is definitely no older plane.</p>
<p>3322 is the number of planes that flew from NYC and are included in the planes table (we used semi_join to reduce the planes table). However, it is precisely the same number that the whole planes table has - meaning that planes table is made of planes that flew from NYC.</p>
</section>
<section id="problem-7-use-the-nycflights13-to-answer-the-following-questions" class="level2">
<h2 class="anchored" data-anchor-id="problem-7-use-the-nycflights13-to-answer-the-following-questions">Problem 7: Use the <code>nycflights13</code> to answer the following questions:</h2>
<pre><code>-   What is the median arrival delay on a month-by-month basis in each airport?
-   For each airline, plot the median arrival delay for each month and origin airport.</code></pre>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Way 1 - save a dataframe grouped by origin and month</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>flights_by_month <span class="ot">&lt;-</span> flights <span class="sc">%&gt;%</span> </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(origin, month)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Way 1 - save the dataframe with summarized valued for median</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>flights_median <span class="ot">&lt;-</span> flights_by_month <span class="sc">%&gt;%</span> </span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">median_arr_delay =</span> <span class="fu">median</span>(arr_delay))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'origin'. You can override using the
`.groups` argument.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Way 1 - try to build faceted scatterplot</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(flights_median, <span class="fu">aes</span>(<span class="at">x =</span> month, <span class="at">y =</span> median_arr_delay)) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_wrap</span>(<span class="sc">~</span> origin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 36 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Flights_NYC_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Way 2 - do the grouping, summarizing and building a graph in one piece of code</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">%&gt;%</span> </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(origin, month) <span class="sc">%&gt;%</span> </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">median_arr_delay =</span> <span class="fu">median</span>(arr_delay)) <span class="sc">%&gt;%</span> </span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> month, <span class="at">y =</span> median_arr_delay) <span class="sc">+</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> origin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'origin'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 36 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Flights_NYC_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>For some reason, R does not calculate the median for arr_delay variable in summarize section. I have used multiple ways to get to the result, but the problem seems to be narrowed down to non-calculating median value.</p>
</section>
<section id="problem-8-lets-take-a-closer-look-at-what-carriers-service-the-route-to-san-francisco-international-sfo.-join-the-flights-and-airlines-tables-and-count-which-airlines-flew-the-most-to-sfo.-produce-a-new-dataframe-fly_into_sfo-that-contains-three-variables-the-name-of-the-airline-e.g.-united-air-lines-inc.-not-ua-the-count-number-of-times-it-flew-to-sfo-and-the-percent-of-the-trips-that-that-particular-airline-flew-to-sfo." class="level2">
<h2 class="anchored" data-anchor-id="problem-8-lets-take-a-closer-look-at-what-carriers-service-the-route-to-san-francisco-international-sfo.-join-the-flights-and-airlines-tables-and-count-which-airlines-flew-the-most-to-sfo.-produce-a-new-dataframe-fly_into_sfo-that-contains-three-variables-the-name-of-the-airline-e.g.-united-air-lines-inc.-not-ua-the-count-number-of-times-it-flew-to-sfo-and-the-percent-of-the-trips-that-that-particular-airline-flew-to-sfo.">Problem 8: Let’s take a closer look at what carriers service the route to San Francisco International (SFO). Join the <code>flights</code> and <code>airlines</code> tables and count which airlines flew the most to SFO. Produce a new dataframe, <code>fly_into_sfo</code> that contains three variables: the <code>name</code> of the airline, e.g., <code>United Air Lines Inc.</code> not <code>UA</code>, the count (number) of times it flew to SFO, and the <code>percent</code> of the trips that that particular airline flew to SFO.</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Join the two tables to enrich flights data with airlines data</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="co"># We want to preserve flights data, hence left join</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>flights_enriched <span class="ot">&lt;-</span> <span class="fu">left_join</span>(<span class="at">x =</span> flights, <span class="at">y =</span> airlines, <span class="at">by =</span> <span class="st">"carrier"</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Take a look at data</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>flights_enriched</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 336,776 × 20
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;          &lt;int&gt;
 1  2013     1     1      517            515         2      830            819
 2  2013     1     1      533            529         4      850            830
 3  2013     1     1      542            540         2      923            850
 4  2013     1     1      544            545        -1     1004           1022
 5  2013     1     1      554            600        -6      812            837
 6  2013     1     1      554            558        -4      740            728
 7  2013     1     1      555            600        -5      913            854
 8  2013     1     1      557            600        -3      709            723
 9  2013     1     1      557            600        -3      838            846
10  2013     1     1      558            600        -2      753            745
# ℹ 336,766 more rows
# ℹ 12 more variables: arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;,
#   tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;,
#   hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;, name &lt;chr&gt;</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interim table to count flights to SFO only by airline</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>fly_into_sfo_only <span class="ot">&lt;-</span> flights_enriched <span class="sc">%&gt;%</span> </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dest <span class="sc">==</span> <span class="st">"SFO"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span> </span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">flights_to_sfo =</span> <span class="fu">n</span>()) </span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Interim table to count total flights by airline</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>fly_total <span class="ot">&lt;-</span> flights_enriched <span class="sc">%&gt;%</span> </span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">%&gt;%</span> </span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">flights_total =</span> <span class="fu">n</span>())</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Join two interim tables to have total flights and flights to SFO in one dataframe</span></span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>fly_into_sfo <span class="ot">&lt;-</span> <span class="fu">left_join</span>(<span class="at">y =</span> fly_total, <span class="at">x =</span> fly_into_sfo_only, <span class="at">by =</span> <span class="st">"name"</span>)</span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a percent variable as ratio of flights to SFO to total flights, arrange from highest to lowest number of flights</span></span>
<span id="cb65-16"><a href="#cb65-16" aria-hidden="true" tabindex="-1"></a>fly_into_sfo <span class="sc">%&gt;%</span> </span>
<span id="cb65-17"><a href="#cb65-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> <span class="fu">round</span>((flights_to_sfo<span class="sc">/</span>flights_total)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">1</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb65-18"><a href="#cb65-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(flights_to_sfo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  name                   flights_to_sfo flights_total percent
  &lt;chr&gt;                           &lt;int&gt;         &lt;int&gt;   &lt;dbl&gt;
1 United Air Lines Inc.            6819         58665    11.6
2 Virgin America                   2197          5162    42.6
3 Delta Air Lines Inc.             1858         48110     3.9
4 American Airlines Inc.           1422         32729     4.3
5 JetBlue Airways                  1035         54635     1.9</code></pre>
</div>
</div>
<p>Only 5 carriers fly to SFO, with United Air Lines Inc.&nbsp;making most flights (6819), but Virgin America focusing on San Francisco destination most (42.6% of its flights).</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>